import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalState } from "./context/GlobalState";
import axios from "axios";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KaizenKlass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  axios.defaults.withCredentials = true;

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Toaster />
          {children}
        </GlobalState>
      </body>
    </html>
  );
}
